***
*** Addition with Peano numbers
*** 

fmod PEANO is
	sort NzNat Even Nat .
	subsorts NzNat Even < Nat .

	op 0 : -> Even [ctor] .
	op s_ : Nat -> NzNat [ctor] .

	op _+_ : Nat Nat -> Nat .

	vars N M : Nat .

	cmb s s N : Even if N : Even .

	eq N + 0 = N .
	eq N + s M = s (N + M) .
endfm

mod PEANO-WITH-RULE is
	protecting PEANO .

	var N : NzNat .

	crl [cancel] : s N => N if N : Even .
endm
