***
*** Implementation of the fust ninja's protocol in «Black Ninjas in the Dark:
*** Formal Analysis of Population Protocols» (10.1145/3209108.3209110).
***

mod NINJAS is
	sorts Mode Vote Ninja Garden .
	subsort Ninja < Garden .

	ops A P : -> Mode [ctor] .
	ops Y N : -> Vote [ctor] .

	op {_,_} : Mode Vote -> Ninja [ctor] .

	op empty : -> Garden [ctor] .
	op __    : Garden Garden -> Garden [ctor assoc comm id: empty] .

	vars V W : Vote .

	rl [r1] : {A, Y} {A, N} => {P, N} {P, N} .
	rl [r2] : {A, V} {P, W} => {A, V} {P, V} .
	rl [r3] : {P, Y} {P, N} => {P, N} {P, N} .
endm
